name: medical-tourism-website
services:
- name: web
  source_dir: /
  github:
    repo: mrselo90/web4
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: NEXTAUTH_SECRET
    value: C7jmwqUvtIMeQf3ylL2kSU/iM6g70yh7mWWPjLIEAoQ=
  - key: NEXTAUTH_URL
    value: https://your-domain.ondigitalocean.app
  - key: NODE_ENV
    value: production
  - key: DATABASE_URL
    value: file:./dev.db
  http_port: 3000 